// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAkyi0TzH5_XCfLx6idJ92UCLX5H2zmv9E',
    appId: '1:734796966829:web:47ed69e53689535ffb0f24',
    messagingSenderId: '734796966829',
    projectId: 'skillsyncai-app',
    authDomain: 'skillsyncai-app.firebaseapp.com',
    storageBucket: 'skillsyncai-app.firebasestorage.app',
    measurementId: 'G-2MB5GJ5FT1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDdeZY9zVEXTmd5K26CXGug7uno-NAuOVM',
    appId: '1:734796966829:android:f776df672b549eb3fb0f24',
    messagingSenderId: '734796966829',
    projectId: 'skillsyncai-app',
    storageBucket: 'skillsyncai-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBiRjzSe9DG8HJVA4W6-hiZXNe4EngjHCI',
    appId: '1:734796966829:ios:b64241aee7ab732efb0f24',
    messagingSenderId: '734796966829',
    projectId: 'skillsyncai-app',
    storageBucket: 'skillsyncai-app.firebasestorage.app',
    iosBundleId: 'com.lingobreeze.app',
  );
}
