// Mocks generated by Mockito 5.4.6 from annotations
// in app/test/features/vocabulary/presentation/providers/vocabulary_notifier_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:app/features/vocabulary/domain/entities/vocabulary_word.dart'
    as _i5;
import 'package:app/features/vocabulary/domain/repositories/vocabulary_repository.dart'
    as _i2;
import 'package:app/features/vocabulary/domain/usecases/vocabulary_usecases.dart'
    as _i3;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeVocabularyRepository_0 extends _i1.SmartFake
    implements _i2.VocabularyRepository {
  _FakeVocabularyRepository_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [GetSavedWords].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetSavedWords extends _i1.Mock implements _i3.GetSavedWords {
  @override
  _i2.VocabularyRepository get repository =>
      (super.noSuchMethod(
            Invocation.getter(#repository),
            returnValue: _FakeVocabularyRepository_0(
              this,
              Invocation.getter(#repository),
            ),
            returnValueForMissingStub: _FakeVocabularyRepository_0(
              this,
              Invocation.getter(#repository),
            ),
          )
          as _i2.VocabularyRepository);

  @override
  _i4.Future<List<_i5.VocabularyWord>> call() =>
      (super.noSuchMethod(
            Invocation.method(#call, []),
            returnValue: _i4.Future<List<_i5.VocabularyWord>>.value(
              <_i5.VocabularyWord>[],
            ),
            returnValueForMissingStub:
                _i4.Future<List<_i5.VocabularyWord>>.value(
                  <_i5.VocabularyWord>[],
                ),
          )
          as _i4.Future<List<_i5.VocabularyWord>>);
}

/// A class which mocks [SaveWord].
///
/// See the documentation for Mockito's code generation for more information.
class MockSaveWord extends _i1.Mock implements _i3.SaveWord {
  @override
  _i2.VocabularyRepository get repository =>
      (super.noSuchMethod(
            Invocation.getter(#repository),
            returnValue: _FakeVocabularyRepository_0(
              this,
              Invocation.getter(#repository),
            ),
            returnValueForMissingStub: _FakeVocabularyRepository_0(
              this,
              Invocation.getter(#repository),
            ),
          )
          as _i2.VocabularyRepository);

  @override
  _i4.Future<void> call(_i5.VocabularyWord? word) =>
      (super.noSuchMethod(
            Invocation.method(#call, [word]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);
}
