// Mocks generated by Mockito 5.4.6 from annotations
// in app/test/features/vocabulary/domain/usecases/vocabulary_usecases_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:app/features/vocabulary/domain/entities/vocabulary_word.dart'
    as _i4;
import 'package:app/features/vocabulary/domain/repositories/vocabulary_repository.dart'
    as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

/// A class which mocks [VocabularyRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockVocabularyRepository extends _i1.Mock
    implements _i2.VocabularyRepository {
  @override
  _i3.Future<List<_i4.VocabularyWord>> getAvailableWords() =>
      (super.noSuchMethod(
            Invocation.method(#getAvailableWords, []),
            returnValue: _i3.Future<List<_i4.VocabularyWord>>.value(
              <_i4.VocabularyWord>[],
            ),
            returnValueForMissingStub:
                _i3.Future<List<_i4.VocabularyWord>>.value(
                  <_i4.VocabularyWord>[],
                ),
          )
          as _i3.Future<List<_i4.VocabularyWord>>);

  @override
  _i3.Future<List<_i4.VocabularyWord>> getSavedWords() =>
      (super.noSuchMethod(
            Invocation.method(#getSavedWords, []),
            returnValue: _i3.Future<List<_i4.VocabularyWord>>.value(
              <_i4.VocabularyWord>[],
            ),
            returnValueForMissingStub:
                _i3.Future<List<_i4.VocabularyWord>>.value(
                  <_i4.VocabularyWord>[],
                ),
          )
          as _i3.Future<List<_i4.VocabularyWord>>);

  @override
  _i3.Future<void> saveWord(_i4.VocabularyWord? word) =>
      (super.noSuchMethod(
            Invocation.method(#saveWord, [word]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);
}
